//Library
export const ADD_BOOKS = "ADD_BOOKS";
export const DELETE_BOOK = "DELETE_BOOK";
export const DELETE_ALL_BOOKS = "DELETE_ALL_BOOKS";

//Fetch

export const FETCH_BOOKS_LOADING = "FETCH_BOOKS_LOADING";
export const FETCH_BOOKS_SUCCES = "FETCH_BOOKS_SUCCES";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";
